import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
      title: "Create Next App",
      description: "Generated by create next app",
};

const montserrat = Montserrat({
      variable: "--sans",
      weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export default function RootLayout({
      children,
}: Readonly<{
      children: React.ReactNode;
}>) {
      return (
            <html lang="en" className={montserrat.className}>
                  <body className="min-h-full flex flex-col">{children}</body>
            </html>
      );
}
